version: "3.9"

services:

  journey-api:
    hostname: journey-api
    container_name: journey-api
    build:
        context: src/
        dockerfile: API/Dockerfile
    environment:
        ASPNETCORE_ENVIRONMENT: Development
    ports:
      - 5043:80
      - 7114:443

  orchestrator:
    hostname: orchestrator
    container_name: orchestrator
    build:
        context: src/
        dockerfile: Orchestrator/Dockerfile
    environment:
        ASPNETCORE_ENVIRONMENT: Development

  challenge-service:
    hostname: challenge
    container_name: challenge
    build:
        context: src/
        dockerfile: Challenge/Dockerfile
    environment:
        ASPNETCORE_ENVIRONMENT: Development
    ports:
      - 5249:80
      - 7221:443

  landmark-service:
    hostname: landmark
    container_name: landmark
    build:
        context: src/
        dockerfile: Landmark/Dockerfile
    environment:
        ASPNETCORE_ENVIRONMENT: Development
    ports:
      - 5251:80
      - 7120:443

  pilgrim-service:
    hostname: pilgrim
    container_name: pilgrim
    build:
        context: src/
        dockerfile: Pilgrim/Dockerfile
    environment:
        ASPNETCORE_ENVIRONMENT: Development
    ports:
      - 5235:80
      - 7103:443

  zipkin:
    image: "openzipkin/zipkin"
    hostname: zipkin
    container_name: zipkin
    ports:
      - 9411:9411

  jaeger:
    image: jaegertracing/all-in-one:1
    hostname: jaeger
    container_name: jaeger
    ports:
      - "6831:6831/udp" # accepts jaeger.thrift over compact thrift protocol
      - "16686:16686" # ui

  postgres:
    image: "postgres:13-alpine"
    hostname: "postgres"
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
        POSTGRES_USER: "user"
        POSTGRES_PASSWORD: "pass"
  
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    container_name: rabbitmq
    ports:
      - "5672:5672" # rabbit itself
      - "15672:15672" # management ui
  
  seq:
    image: "datalust/seq:2021"
    hostname: seq
    container_name: seq
    ports:
      - "5341:5341" # ingestion API
      - "5555:80" # ui
    environment:
        ACCEPT_EULA: "Y"

