version: "3.9"

services:

  journey-api:
    hostname: journey-api
    container_name: journey-api
    build:
        context: src/
        dockerfile: API/Dockerfile
    environment:
        ASPNETCORE_ENVIRONMENT: Development
    ports:
      - 5043:80

  orchestrator:
    hostname: orchestrator
    container_name: orchestrator
    build:
        context: src/
        dockerfile: Orchestrator/Dockerfile

  challenge-service:
    hostname: challenge
    container_name: challenge
    build:
        context: src/
        dockerfile: Challenge/Dockerfile

  landmark-service:
    hostname: landmark
    container_name: landmark
    build:
        context: src/
        dockerfile: Landmark/Dockerfile

  pilgrim-service:
    hostname: pilgrim
    container_name: pilgrim
    build:
        context: src/
        dockerfile: Pilgrim/Dockerfile

  jaeger:
    image: jaegertracing/all-in-one:1
    hostname: jaeger
    container_name: jaeger
    ports:
      - "6831:6831/udp" # accepts jaeger.thrift over compact thrift protocol
      - "16686:16686" # ui

  postgres:
    image: "postgres:13-alpine"
    hostname: "postgres"
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
        POSTGRES_USER: "user"
        POSTGRES_PASSWORD: "pass"
  
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    container_name: rabbitmq
    ports:
      - "5672:5672" # rabbit itself
      - "15672:15672" # management ui
